[build-system]
requires = ["maturin>=1.5,<2.0"]
build-backend = "maturin"

[project]
name = "misah"
requires-python = ">=3.9"
description = "Rust-based geospatial kernels with Python bindings"
authors = [{ name = "mauroalberti", email = "alberti.m65@gmail.com" }]
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
]
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
