[package]
name = "misah"
version = "0.2.0"
authors = ["mauroalberti <alberti.m65@gmail.com>"]
description = "A crate for structural geology processings."
license = "GPL-3.0-or-later"
readme = "../README.md"
repository = "https://gitlab.com/mauroalberti/misah"
exclude = [
    "test.*",
    "examples/*.svg"
]
keywords = ["earth-sciences", "structural-geology"]
categories = ["science"]
edition = "2021"

[dependencies]
ndarray = "0.15.4"
rusqlite = { version = "0.31", features = ["bundled"] }
thiserror = "1"

[lib]
name = "misah"
path = "src/lib.rs"

